name: Rust

on:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  CARGO_INCREMENTAL: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MOZJS_CREATE_ARCHIVE: 1

jobs:
  linux:
    env:
      RUSTC_WRAPPER: "sccache"
      CCACHE: sccache
      SCCACHE_GHA_ENABLED: "true"
    runs-on: ubuntu-22.04 # Needed for artifacts to work on older systems (due to glibc)
    strategy:
      fail-fast: false
      matrix:
        features: ['""']
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        run: |
          sudo apt install llvm musl -y
          rustup target add riscv64gc-unknown-linux-musl
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: Build
        run: |
          cargo build --verbose --features ${{ matrix.features }} --target riscv64gc-unknown-linux-musl
      - name: Check wrappers integrity
        # we generate wrappers only without debugmozjs
        if: ${{ matrix.features != 'debugmozjs' }}
        run: |
          bash ./mozjs/src/generate_wrappers.sh
          git diff --quiet --exit-code
